### ISSUE TITLE
GND SPARQL endpoint returns no results

### ISSUE THREAD

**Issue by reckart** [zbw/sparql-queries#9]
Is there a problem with the GND endpoint?

Even the default example query returns no results anymore:

https://zbw.eu/beta/sparql-lab/?endpoint=http://zbw.eu/beta/sparql/econ_pers/query&queryRef=https://api.github.com/repos/jneubert/sparql-queries/contents/econ_pers/search_concepts_by_text.rq

**Comment by reckart** [comment]
This query also returns no results anymore:

```
PREFIX text: <http://jena.apache.org/text#>
SELECT DISTINCT ?m ?subj
WHERE { { { OPTIONAL { ?pMatch <http://www.w3.org/2000/01/rdf-schema#subPropertyOf>* <http://www.w3.org/2000/01/rdf-schema#label> . }
{ ( ?subj ?sc ?m ) text:query ( ?pMatch "thomas henricus" ) .
FILTER ( ( ( REGEX( ?m, "^Thomas\\s+Henricus$", "i" ) && LANGMATCHES( LANG( ?m ), "en" ) ) || ( REGEX( ?m, "^Thomas\\s+Henricus$", "i" ) && LANGMATCHES( LANG( ?m ), "" ) ) ) ) } } } }
LIMIT 200
```

**Comment by jneubert** [comment]
First of all, since yesterday the GND endpoint has been created anew (with dataset 2021-11, on another machine, with the current development version of Fuseki and TDB2), so *maybe* things have changed.

However, it looks like your "Thomas Henricus" query works, when you comment out the regex filter. 

Not sure why the regex worked before - the only occurence of the exact string in the current source file is
````
<https://d-nb.info/gnd/100136605> gndo:variantNameForThePerson "Gadebusch, Thomas Henricus";
  gndo:variantNameEntityForThePerson _:node1fhgbdto1x8884759 .

_:node1fhgbdto1x8884759 gndo:forename "Thomas Henricus";
  gndo:surname "Gadebusch" .
````
The example query is for the econ_pers dataset (derived from a long-outdated GND version - even before the gndo URIs switched to https). Additionally, the GND does not include skos:prefLabels.

But thanks anyway, and please let me know if other issues occur.

**Comment by jneubert** [comment]
MisterSynergy (Wikidata) found another issue with gndo:DifferentiatedPerson:
```
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT DISTINCT *
WHERE {
  ?x a gndo:DifferentiatedPerson .
}
LIMIT 10
```
yields no results.

**Comment by reckart** [comment]
Thanks for the feedback. When I adjust the query to include the last name as well, it works! So for me, the issue could be closed - but maybe you want to keep it open because of the other query that returns no results.

**Comment by jneubert** [comment]
The load process on weekend did not terminate correctly. Now the dataset from another load is live and seems to work correctly. @MisterSynergy: Would be nice if you could check with your queries.

**Comment by MisterSynergy** [comment]
Yes, this works for me as well now. Thanks for the fix!
